### ISSUE TITLE
Embassy Town

### ISSUE THREAD

**Issue by interfect** [decentraland/districts#19]
It might make sense to have a district where other projects can have official embassies in Decentraland. I'm planning to build one for my [Macroverse](https://macroverse.io) project, and if other people also want similar spaces, I would want mine to be near theirs. We could have installations from things like Second Life, various MMOs (or maybe guilds within MMOs, or cross-game guilds), maybe something from Bitnation, and so on.

I would anticipate that each embassy would be about 1 LAND big.

**Comment by dclancy13** [comment]
I really like this idea. I think it works well with the [Tech Sector Proposal](https://github.com/decentraland/districts/issues/11) by Andrew Mazzola https://github.com/admazzola
There should be a place where VR/ Blockchain / DLT projects have an common "workspace" where they can run their businesses remotely. It will turn this project (and the DCL Metaverse in general) into a hub for the whole industry and will help it succeed.

**Comment by interfect** [comment]
Here's a more formal proposal, in the requested format:


1. Title:  **Embassy Town**
2. Description: Other virtual world, metaverse, and MMO projects can benefit from opening "embassies" in Decentraland: installations where each game or project can advertise itself to Decentraland players. Embassy Town is intended to be a central location for such embassies. Players looking for more games to play or more virtual worlds to explore will benefit from being able to browse through the available options in one place. Eventually, players might be able to sign up for other projects or games directly through the relevant embassy, paying any subscription costs in MANA. Competing projects will not cannibalize each others' prospective players, because in general players will want to participate in more than one virtual world. If the Embassy Town district is relatively popular, other districts might even want to open their own embassies, to attract visitors.
3. Project Lead: Adam Novak <interfect@gmail.com>
4. Team: Adam Novak <interfect@gmail.com>, Organizer
5. Goal:  Cross-promote different virtual world projects.
6. Category: Public
7. LAND Needed: At least 1 LAND per embassy.
8. Startup Costs: $0 (each project must design and construct its own embassy), plus at least 1000 MANA per embassy for LAND purchase.
9. How will funds be raised: Participating projects will devote some of their project budgets towards constructing their own embassies.
10. How will contributors see a return value: Participants in the district during the Terraform Event will only benefit from owning land in the district if they use it to construct an embassy for their project and successfully market it to visiting players. Staking 1000 MANA towards the district buys 1 LAND in the district, and each participant may buy as much LAND in the district as they wish.
11. Attachments / Designs / Budgets: As an initial design guideline, embassies should reserve 1-meter strips all the way around their perimeters for sidewalks. The sidewalks of adjacent embassies should match each other in height and look-and-feel. This would result in a hexagonal grid of 2 meter wide paths between all the embassies, which sounds sufficient. If navigability (or having zig-zagging roads) becomes a problem, new design guidelines can be agreed on by community consensus.

**Comment by alex-core-0x** [comment]
I'm the developer of SCRIV network - the project of assurance, verification and timestamping of any data. 
Checkout our whitepaper on the website: http://scriv.network/
And also i own 1 parsel in this district. 
Feel free to message me if you will have any idea how we can cooperate: lova@scriv.network

**Comment by interfect** [comment]
As far as actually getting the district off the ground goes:

It looks like Decentraland the company wants each district to write a
"Startup Plan" and hold a land-weighted address-signed vote on the plan
before turning over control of the LAND parcels.

The plan for this district is probably a private ownership model (i.e. each
participant actually owns privately the parcels they put in for), but we
still need to work out a division of the plot that Decentraland allocated
and an official set of building guidelines.

I'm having trouble getting into the auction UI at the moment, so if anyone
has a screenshot of the district's assigned plot that would be very
helpful. It would also be good if people could sound off here with the
amount of LAND in the district they contributed for, so we know who can be
expected to actually vote in a vote. So far we have:

@GitMyCodeUp: 1 LAND
@interfect: 1 LAND

**Comment by interfect** [comment]
OK, I managed to get the land manager working.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/752054/37498729-25089846-287d-11e8-8c48-c1198d247cbb.png)

Does anyone have a preference for a particular LAND?

**Comment by alex-core-0x** [comment]
@interfect are you a distributor?
I like to have this one, if no one objects.
![untitled](https://user-images.githubusercontent.com/4012243/37508083-2d0e6ad4-28fa-11e8-9e0d-32e6dc5718bf.png)

**Comment by interfect** [comment]
I just proposed the district, and the Decentraland folks added me to all
the district leader file shares/channels. So I guess I'm in charge right
now? But I'm not as strongly involved in Decentraland as I could be, so if
someone else wants the job let me know.

I have no objection to you taking that plot. I am going to go ahead and
reserve the one right to the left of it I think.

**Comment by interfect** [comment]
OK, I've made a Google Form to collect people's land desires and Ethereum addresses and contact info. Once we have a complete list of preferences, I can make a final breakdown as an official proposal satisfactory to Decentraland. Then we all have to vote verifiably, by signing things with our ETH addresses, and then we can get the LAND distributed, hopefully.  I also finally found the list of contributor addresses, too, so everyone can just tell me their ETH address and I can know how much land they should get.

Everyone who contributed to the district, please fill out this survey: https://docs.google.com/forms/d/e/1FAIpQLSd6yD4o65ePDKxuYheYyujyZTC7c9KslD8XtMT0L9gkJdxA1Q/viewform

Please fill this out **within 2 weeks from now**. That's when I hope to make the breakdown, so if you don't fill it out you'll be assigned LAND from what's left and won't get a personal e-mail to participate in the proposal vote.

@GitMyCodeUp Can you please fill it out again with your parcel selection? I will too.

**Comment by interfect** [comment]
OK, I've talked to some Decentraland folks, and it seems that, since we weren't able to get more than half of the contributors by LAND weight together to sign off on an official district proposal document with an on-chain vote by the deadline they instituted, they are going to or have already unwound the whole district and returned people's contributed MANA. Sorry everyone; Embassy Town is not going to happen.

**Comment by alex-core-0x** [comment]
WTF? Nobody cares about MANA. We need a district :-\

**Comment by interfect** [comment]
If you'd like to take the lead on the project, I'd be quite happy. I think the next step, if you want to somehow make it happen, would be either to hold a token-weighted vote on a land distribution plan and associated district proposal written Decentraland's satisfaction (and then to convince Decentraland to accept the result of the vote whether or not a quorum of stakers actually bother to participate, and despite it being after whatever deadlines they decreed), or to convince Decentraland to hand out the LAND to stakers by some partition without such a vote.

I don't actually see a refund of any of my staked MANA for the district, so presumably they haven't processed the refunds yet. So it comes down to convincing Decentraland, who hold the actual relevant private keys as far as I can tell, to do what you want, using some combination of requests, offers to pay them, and threats of or actual legal action on the basis of the promises and representations that were made to stakers at the time of the token sale.

I'm not much happier with the situation than you are, but I've already hit the maximum amount of unpaid work I'm willing to do over the ~$70 of tokens I staked. Let this be a lesson to us all to put out trust in actual deployed smart contract code over the sort of send-tokens-directly-to-[puppet-contract](https://etherscan.io/address/0xcca95e580bbbd04851ebfb85f77fd46c9b91f11c#code), sign-a-message-and-hope logic on which the district staking system was based.

**Comment by alex-core-0x** [comment]
I've personally got 2 another my crypto projects-businesses, so will not have time to take care about this on. Probably we will have another desirous person.
