### ISSUE TITLE
MusicHub

### ISSUE THREAD

**Issue by ahaedike** [decentraland/districts#40]
The district of musicians, fans, producers, and media.  Come to listen to the latest tracks produced by residents, stay for live concerts.  Sit in on a jam session.  Collaborate with other residents on new music created in a new distributed asynchronous way.  Maybe just chill and enjoy some new music.

Stop by often, you may be surprised by a popular artist that pops in and gives an impromptu concert.  Bloggers and magazines come here to interview rising talent.  Musicians promote their latests tracks.  Residents share their latest discoveries in new music and find new tracks.  Sometimes tracks are purposely hidden for you to discover.

Virtual recording studios allow residents creative freedom.  
Of course, there are dance clubs for DJ's to work on their sets.

District could be sub-divided by genre.

![screen shot 2017-09-29 at 10 00 49 am](https://user-images.githubusercontent.com/170821/31027004-7ea4c428-a4fd-11e7-8302-2502dfb8791d.png)

![screen shot 2017-09-29 at 9 50 47 am](https://user-images.githubusercontent.com/170821/31027015-8b706b62-a4fd-11e7-9c91-0d339c2b9d2e.png)

![screen shot 2017-09-29 at 9 51 42 am](https://user-images.githubusercontent.com/170821/31027031-971dfd76-a4fd-11e7-8650-0df05965e9e8.png)

**Comment by Platosbuilder** [comment]
Cool design! What can we do to go forward?

**Comment by RockstarReality** [comment]
I want in =)

**Comment by petey702** [comment]
Hey! im pretty invested in this project. can we make a discord channel for communication?

**Comment by flatyoder** [comment]
Hey I'm looking for a place to stay in touch on this district. I only own a plot over here, but have some technical background in programming. Let me know if I can find you all on rocket chat or discord or wherever. Happy New Years!!

**Comment by ahaedike** [comment]
Hi... Happy New Year to everyone.  Open to rocket chat or discord... was waiting a bit longer to see who else is invested in this project.  FYI... I am a software developer and proposed the concept.  Now that the auction dust is settling, can start to put some plans together.  Thanks.

**Comment by petey702** [comment]
great. we r chomping at the bit! i prefer discord. id like to b deeply involved in this project. some programming, music experience. Lets get a rocketchat room going on chat.decentraland.org , then we can set up a google questionnaire for investors,, discord and move on from there.
Happy new year

**Comment by trislit** [comment]
It looks like this was closed in September 2017. What are the plans moving forward?

**Comment by petey702** [comment]
^^^^ this. are there any plans? and.. please respond now or a new leadership will need to be appointed. a 51%+ majority of the contributors have expressed interest in getting things going.

**Comment by ahaedike** [comment]
Hello... interest seems to come in waves.  I am consumed with other projects at the moment.  Happy to turn leadership over to motivated parties.  Would like to see it go, but can not lead at the moment.   There were parcels staked for this project during the terraform and we must be sure those developers are represented.  Suggestions?

**Comment by trislit** [comment]
I have been trying to work with petey702 on a plan of action to get contributors involved and to start working on an initial dev/funding plan. I can run with the leadership role for the time being if that is alright, but for the decentraland team to officially recognize it we need to get an initial plan voted on by contributors. I am trying to collect contributors contact information and skills/development help suggestions at https://trislit.typeform.com/to/r7u0FS , and discussion surrounding decentraland and music hub specificly has moved to discord at https://discord.gg/UyZkpcM  I think this is important  as there may be some different interpretations of what this project should and should not become, and I want everyone to have a say in this.
