### ISSUE TITLE
Auto Moto Aero ShowSpace 

### ISSUE THREAD

**Issue by Denis17DCL** [decentraland/districts#58]
I think the idea of having a full VR experince with new car or aircraft would be great
So lets have Mercedes and BMW in DCL

**Comment by QuillzLouis** [comment]
> When submitting a district, please include:

    Title: Name of District
    Description: Discuss in a paragraph the details of your Proposal
    Project Lead: Name and Email
    Team: Name / Email / Roles of each committed team member (list no more than 5 members)
    Goal:  What does this District want to accomplish (i.e. generate revenue for its owners, act as a public gathering place, just be for fun)
    Category: Private / Public
    LAND Needed: How Much LAND will be required to successfully launch this District
    Startup Costs: How much (in USD) will be needed to fund building the District (pay for developers / designers / marketing)
    How will funds be raised: Explain how startup costs will be raised to complete and launch the District
    How will contributors see a return value: Explain why others would want to participate in this District
    Attachments / Designs / Budgets: Upload any supporting files.

**Comment by Denis17DCL** [comment]
Title: Auto Moto Show
Description: The idea is to have auto brands show rooms in full VR
Project Lead: Denis Chistyakov
Team: Name / Email / Not yet
Goal: Generate revenue buy creating and showing VR models to the public
More clicks more revenue
Category: Private  
LAND Needed:  1000
Startup Costs:  NDA
How will funds be raised:  NDA
How will contributors see a return value: Explain why others would want to participate in this District - Land owners do not need to have VR development skills in order to own a profitable show room. We need turnkey solution, which consists in a high quality building and a fully operational  show room
Attachments / Designs / Budgets: NDA

**Comment by Denis17DCL** [comment]
The idea is very raw, i want to see if i have enough support from the community

**Comment by Denis17DCL** [comment]
Imagine, you can be inside the working engine :)

**Comment by Denis17DCL** [comment]
These showrooms also can be used by autoproducers for learning classes with their staff
Imagine, you can be inside the working engine :)
