### ISSUE TITLE
 QuestMegaRoom

### ISSUE THREAD

**Issue by Denis17DCL** [decentraland/districts#59]
Idea is to have lots of VRquests under one roof

**Comment by QuillzLouis** [comment]
> When submitting a district, please include:

    Title: Name of District
    Description: Discuss in a paragraph the details of your Proposal
    Project Lead: Name and Email
    Team: Name / Email / Roles of each committed team member (list no more than 5 members)
    Goal:  What does this District want to accomplish (i.e. generate revenue for its owners, act as a public gathering place, just be for fun)
    Category: Private / Public
    LAND Needed: How Much LAND will be required to successfully launch this District
    Startup Costs: How much (in USD) will be needed to fund building the District (pay for developers / designers / marketing)
    How will funds be raised: Explain how startup costs will be raised to complete and launch the District
    How will contributors see a return value: Explain why others would want to participate in this District
    Attachments / Designs / Budgets: Upload any supporting files.

**Comment by Denis17DCL** [comment]
Title: QuestMegaRoom
Description:  Idea is to have lots of VRquests under one roof (in different locations in DCL with possible move from one quest to another and from virtual to real)
Project Lead: Denis Chistyakov d.chistyakov@me.com
Team: Not yet
Goal:  Generate revenues by selling tickets to enter the quest
Category: Private  
LAND Needed:  100 in different locations and districts
Startup Costs:  No idea
How will funds be raised:  Enthusiasts like me will discuss it in a separate channel
How will contributors see a return value:  Ideally this project needs people with quest creation experince, so they can contribute with ideas, not only land and money
Attachments / Designs / Budgets:  Being researched

**Comment by petey702** [comment]
I'd like to offer a pivot to this. a district where you will be able to only do things in parties.. parties of 2+ but it doesnt matter right now. in the district we could have the quest room, "game show" rooms, and any other fun group activites. if you decline, theres no hard feelings. i will just create a new district for it
