### ISSUE TITLE
Shwedagon Pagoda

### ISSUE THREAD

**Issue by Denis17DCL** [decentraland/districts#60]
Full size - beautiful Swedagon Pagoda - 100% replica of a real one
Inside the Pagoda you will be able to see all famous stories from the life of the Buddha  
It is a charity project

**Comment by QuillzLouis** [comment]
When submitting a district, please include:

    Title: Name of District
    Description: Discuss in a paragraph the details of your Proposal
    Project Lead: Name and Email
    Team: Name / Email / Roles of each committed team member (list no more than 5 members)
    Goal:  What does this District want to accomplish (i.e. generate revenue for its owners, act as a public gathering place, just be for fun)
    Category: Private / Public
    LAND Needed: How Much LAND will be required to successfully launch this District
    Startup Costs: How much (in USD) will be needed to fund building the District (pay for developers / designers / marketing)
    How will funds be raised: Explain how startup costs will be raised to complete and launch the District
    How will contributors see a return value: Explain why others would want to participate in this District
    Attachments / Designs / Budgets: Upload any supporting files.

**Comment by Denis17DCL** [comment]
Title: Shwedagon Pagoda
Description: beautiful Swedagon Pagoda - 100% replica of a real one
Inside the Pagoda you will be able to see all famous stories from the life of the Buddha
Project Lead: Denis Chistyakov d.chistyakov@me.com
Team:  Not yet
Goal:   It is a public gathering place, neighbouring land parcels might get benefit as it happens in real life in Asia 
Category:  Public
LAND Needed: Real Shwedagon Complex is around 5 hectars
 https://www.airpano.ru/files/Shwedagon-Pagoda-Myanmar/2-2Startup Costs: 
How much (in USD) will be needed to fund building the District (pay for developers / designers / marketing) Really have no idea - about the budget
How will funds be raised: Explain how startup costs will be raised to complete and launch the District I will promote this project amongst Buddhist community
How will contributors see a return value: Explain why others would want to participate in this District This is a charity project, possible income may be generated if you have land near the Pagoda
Attachments / Designs / Budgets:  https://www.airpano.ru/files/Shwedagon-Pagoda-Myanmar/2-2

**Comment by Denis17DCL** [comment]
I am very open to this idea - please write your ideas if you see any interest in this
