### ISSUE TITLE
#6 Altcoin Rollercoaster Park

### ISSUE THREAD

**Issue by rongomaib** [decentraland/districts#7]
A rollercoaster themepark with rides based on historical and/or live price charts.

Mana can be spent to change the current rides for all users on DCL.

**Comment by UXVirtual** [comment]
+1 for this

**Comment by EmmaMakhno** [comment]
can it have a troll box FUD theme

**Comment by rongomaib** [comment]
this was just a joke... closing.

**Comment by rongomaib** [comment]
Ok someone has staked 13 LAND... now what?!

**Comment by eordano** [comment]
Closed
